# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Torsten Knodt

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    assignees:
      - torsknod2
    reviewers:
      - copilot
      - torsknod2
    labels:
      - "type:ci"
      - "auto:bot"
    commit-message:
      prefix: "ci"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    assignees:
      - torsknod2
    reviewers:
      - copilot
      - torsknod2
    labels:
      - "auto:dependencies"
      - "auto:bot"
      - "lang:python"
    commit-message:
      prefix: "build(deps)"
